In [1]:
# Q1. Import numpy as `np` and print the version number.
import numpy as np
np.version.version

'1.24.3'

In [2]:
# Q2. Create a 1D array of numbers from 0 to 9.
a=np.arange(1,10,1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Q3. Extract all odd numbers from numpy array.
a=np.arange(1,10,1)
a[a%2!=0]

array([1, 3, 5, 7, 9])

In [4]:
# Q4. Replace all odd numbers in array with -1.
a=np.arange(1,10,1)
a[a%2!=0]=-1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1]


In [5]:
# Q5. Convert a 1D array to a 2D array with 2 rows.
a=np.arange(1,9,1)
print(a)
np.reshape(a,(2,4))

[1 2 3 4 5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# Q6. Stack the arrays a and b horizontally.
a=np.random.randint(1,5,(3,4))
b=np.random.randint(1,5,(3,4))
print(a)
print(b)
c=np.concatenate([a,b],axis=1)
print(c)

[[3 3 2 4]
 [4 4 4 4]
 [2 4 3 3]]
[[1 2 2 3]
 [2 2 3 3]
 [2 3 3 2]]
[[3 3 2 4 1 2 2 3]
 [4 4 4 4 2 2 3 3]
 [2 4 3 3 2 3 3 2]]


In [19]:
# Q6. Stack the arrays a and b horizontally.
a=np.random.randint(1,5,(3,4))
b=np.random.randint(1,5,(3,4))
print(a)
print(b)
c=np.hstack((a,b))
print(c)

[[2 1 4 3]
 [1 3 3 3]
 [1 2 3 1]]
[[2 2 3 1]
 [3 4 4 4]
 [3 3 1 2]]
[[2 1 4 3 2 2 3 1]
 [1 3 3 3 3 4 4 4]
 [1 2 3 1 3 3 1 2]]


In [18]:
# Q7. Get the common items between a and b.
a=np.random.randint(1,5,(3,4))
print(a)
b=np.random.randint(1,5,(3,4))
print(b)
c=np.intersect1d(a,b)
print(c)

[[4 3 3 1]
 [1 1 3 2]
 [2 4 3 3]]
[[1 1 1 1]
 [4 2 4 2]
 [4 1 2 4]]
[1 2 4]


In [15]:
# Q8. From array a remove all items present in array b.
a=np.random.randint(1,5,6)
print(a)
b=np.random.randint(1,5,6)
print(b)
np.setdiff1d(a,b)

[3 4 2 3 1 3]
[1 1 2 3 2 3]


array([4])

In [17]:
# Q9. Get the positions where elements of a and b match.
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,4,8])
print(a)
print(b)
np.where(a==b)

[1 2 3 4 5]
[4 5 6 4 8]


(array([3], dtype=int64),)

In [20]:
# Q10. Get all items between 5 and 10 from a.
a=np.random.randint(1,10,8)
print(a)
np.where((a>=5) & (a<10))

[8 4 3 9 8 2 4 9]


(array([0, 3, 4, 7], dtype=int64),)