In [1]:
import numpy as np
a=np.array([10,20,30])
print(type(a))
print(a)
print([10,20,30])

<class 'numpy.ndarray'>
[10 20 30]
[10, 20, 30]


In [2]:
a=np.array([10,20,30,4.5])
print(a)

[10.  20.  30.   4.5]


In [3]:
a=np.array([10,20,30,4.5,'sonu'])
print(a)

['10' '20' '30' '4.5' 'sonu']


In [4]:
a=np.array([10,20,30,4.5],dtype=np.int32)
print(a)

[10 20 30  4]


In [5]:
a=np.array([10,20,30,4.5],dtype=np.float32)
print(a)

[10.  20.  30.   4.5]


In [8]:
# a=np.array([10,20,30,4.5,'sonu'],dtype=np.float32)
# print(a) error

In [9]:
a=np.array([128,20,30,40],dtype=np.int8)
print(a)

[-128   20   30   40]


C:\Users\Raju\AppData\Local\Temp\ipykernel_15364\3309133021.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a=np.array([128,20,30,40],dtype=np.int8)


In [10]:
a=np.arange(1,10,1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [11]:
a=np.arange(1,10,0.5)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [13]:
range(1,10,2)

range(1, 10, 2)

In [15]:
# range(1,10.5,0.5) error

In [2]:
import numpy as np

In [3]:
x=list(range(5000))
y=np.arange(5000)
import sys
print(sys.getsizeof(x))
print(sys.getsizeof(y))

40056
20112


In [4]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [5]:
a=np.zeros(5,dtype=np.int32)
print(a)

[0 0 0 0 0]


In [9]:
a=np.zeros(5)
a[-1]=50
print(a)

[ 0.  0.  0.  0. 50.]


In [10]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [11]:
a=np.ones(5,dtype=np.int32)
a[0]=100
print(a)

[100   1   1   1   1]


In [12]:
a=np.full(3,10)
print(a)

[10 10 10]


In [13]:
a=np.linspace(10,100,5)
print(a)

[ 10.   32.5  55.   77.5 100. ]


In [14]:
a=np.linspace(10,100,10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [15]:
a=np.linspace(10,100)
print(a)

[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ]


In [16]:
a=np.random.randint(1,100,5)
print(a)

[96 26 30 55 36]


In [17]:
a=np.random.uniform(1,100,5)
print(a)

[68.67197168 23.34790007 72.44270573 29.17808613 46.39562672]


In [18]:
a=np.random.randint(1000,9999)
print(a)

8503


In [19]:
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
print(x)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [20]:
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
import random
y=random.choices(x,k=5)
print(y)

['3', '1', 'v', '5', '9']


In [22]:
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
y=random.choices(x,k=5)
s=""
for i in y:
    s=s+i
print(s)    

2AKJT


In [23]:
a=np.loadtxt("d:/load.txt")
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
a=np.loadtxt("d:/load.txt",delimiter=None)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [25]:
a=np.loadtxt("d:/load1.txt",delimiter=",")
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [27]:
# a=np.loadtxt("d:/load1.txt")
# print(a) error

In [28]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
a=np.full((3,4),6)
print(a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [33]:
a=np.random.randint(1,100,(3,3))
print(a)

[[50 16 89]
 [65 70 28]
 [91 68 81]]


In [34]:
a=np.random.uniform(1,100,(3,3))
print(a)

[[99.62988427 29.77767232 27.16682926]
 [77.36948649 41.89477264 89.35966424]
 [ 2.14029113 19.8069249  72.31270835]]


In [35]:
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
