In [2]:
import statistics as stats
x=[4,5]
print(stats.mean(x))
print(stats.geometric_mean(x))
print(stats.harmonic_mean(x))

4.5
4.472135954999579
4.444444444444445


In [3]:
x=[6,2,8,10,5,9,11]
print(stats.median(x))
x=[6,2,8,10,5,9,11,6]
print(stats.median(x))
x=[6,2,8,10,5,9,11,6]
print(stats.median_low(x))
x=[6,2,8,10,5,9,11,6]
print(stats.median_high(x))

8
7.0
6
8


In [4]:
x=[6,2,8,10,5,9,11,6]
print(stats.median(x))
print(stats.mean(x))

7.0
7.125


In [5]:
x=[6,2,8,100,5,9,11,6]
print(stats.median(x))
print(stats.mean(x))

7.0
18.375


##### Quantiles [q1(25%),q2(50%),q3(75%)]

In [6]:
import random 
x=[]
for i in range(50):
    v=random.randint(20,150)
    x.append(v)
print(x)

[47, 49, 145, 69, 138, 131, 76, 34, 92, 67, 123, 137, 26, 69, 123, 112, 39, 121, 27, 50, 42, 84, 65, 35, 112, 138, 43, 35, 23, 106, 39, 22, 131, 118, 132, 115, 97, 109, 64, 122, 93, 63, 31, 115, 25, 115, 145, 114, 91, 100]


In [7]:
import random 
x=[]
for i in range(50):
    v=random.randint(20,150)
    x.append(v)
q1,q2,q3=stats.quantiles(x)
print(q1,q2,q3)

58.75 89.0 117.25


#### outliers(Anomalies) 

In [8]:
x[0]=500
x[10]=-400
print(x)

[500, 60, 71, 68, 91, 108, 134, 100, 55, 147, -400, 122, 38, 145, 107, 109, 85, 140, 26, 63, 92, 35, 150, 72, 27, 20, 121, 135, 144, 34, 131, 27, 68, 104, 41, 86, 82, 92, 23, 116, 134, 86, 67, 122, 87, 38, 41, 107, 97, 82]


In [9]:
q1,q2,q3=stats.quantiles(x)
print(q1,q2,q3)
iqr=q3-q1
print(iqr)
for i in x:
    if i<(q1-1.5*iqr):
        print(i,"low outlier")
    elif i>(q3+1.5*iqr):
        print(i,"high outlier")

51.5 86.5 121.25
69.75
500 high outlier
-400 low outlier


##### standard deviation(std)

In [10]:
x=[40,60,80]
y=[59,60,61]
z=[60,60,60]
print(stats.mean(x),stats.stdev(x))
print(stats.mean(y),stats.stdev(y))
print(stats.mean(z),stats.stdev(z))

60 20.0
60 1.0
60 0.0


#### Mode

In [11]:
import statistics as stats
x=[2,1,3,2,3,1,2]
print(stats.mode(x))


2


In [12]:
x=[2,1,3,2,3,1,2,'a','b','a','a']
print(stats.mode(x))

2


In [13]:
x=[2,1,3,2,1,2,3,1]
print(stats.mode(x))
print(stats.multimode(x))

2
[2, 1]


In [14]:
distance=[200,150,400]
fuel=[20,15,30]
print(stats.correlation(distance,fuel))

0.989743318610787


In [15]:
speed=[100,60,120,90]
time=[3,5,2,5]
print(stats.correlation(speed,time))

-0.8666666666666667


In [16]:
roll=[1,2,3,4]
marks=[80.5,56.4,70,39]
print(stats.correlation(roll,marks))

-0.7980658410632766


In [17]:
p=[1,2,3,4,5,6,7,8,9,10]
print(random.sample(p,k=4))
print(random.choices(p,k=4))

[5, 9, 7, 4]
[10, 8, 10, 4]


In [18]:
p=[1,2,3,4,5,6,7,8,9,10]
print(random.choices(p,k=12))
print(random.sample(p,k=12))

[10, 6, 3, 8, 6, 6, 10, 5, 2, 7, 9, 4]


ValueError: Sample larger than population or is negative

In [19]:
p=[1,2,3,4,5,6,7,8,9,10]
print(stats.pstdev(p))
print(stats.stdev(p))

2.8722813232690143
3.0276503540974917


In [ ]:
p=[1,2,3,4,5,6,7,8,9,10]
print(stats.pvariance(p))
print(stats.variance(p))

8.25
9.166666666666666


In [20]:
import numpy as np
a=np.array([10,20,30])
print(type(a))
print(a)
print([10,20,30])

<class 'numpy.ndarray'>
[10 20 30]
[10, 20, 30]


In [21]:
a=np.array([10,20,30,4.5])
print(a)
a=np.array([10,20,30,4.5,'sonu'])
print(a)

[10.  20.  30.   4.5]
['10' '20' '30' '4.5' 'sonu']


In [22]:
a=np.array([10,20,30,4.5],dtype=np.int32)
print(a)

[10 20 30  4]


In [23]:
a=np.array([10,20,30,4.5])
print(a)

[10.  20.  30.   4.5]


In [24]:
a=np.array([128,20,30,40],dtype=np.int8)
print(a)

[-128   20   30   40]


C:\Users\Raju\AppData\Local\Temp\ipykernel_21768\3309133021.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a=np.array([128,20,30,40],dtype=np.int8)


In [25]:
a=np.array([128,20,30,40],dtype=np.uint8)
print(a)

[128  20  30  40]


In [26]:
a=np.arange(1,10,1)
print(a)
a=np.arange(1,10,0.5)
print(a)

[1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [27]:
import sys
x=list(range(5000))
y=np.arange(5000)
print(x)
print(y)
print(sys.getsizeof(x))
print(sys.getsizeof(y))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [28]:
a=np.zeros(5)
print(a)
a=np.zeros(5,dtype=np.int32)
print(a)
a=np.zeros(5,dtype=np.int64)
print(a)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0 0 0 0 0]


In [29]:
a=np.zeros(5)
a[-1]=50
print(a)

[ 0.  0.  0.  0. 50.]


In [30]:
a=np.ones(5)
a[-1]=100
print(a)

[  1.   1.   1.   1. 100.]


In [31]:
a=np.full(5,23)
print(a)

[23 23 23 23 23]


In [32]:
a=np.full(5,23)
a[-2]=57
print(a)

[23 23 23 57 23]


In [33]:
a=np.linspace(1,50,5)
print(a)

[ 1.   13.25 25.5  37.75 50.  ]


In [34]:
a=np.random.randint(1,100,5)
print(a)

[60 52 65 47 26]


In [35]:
a=np.random.uniform(1,100,5)
print(a)

[28.54407338 37.54367194 18.85693631 93.40652196 18.37205777]


In [28]:
a=np.random.randint(1000,9999)
print(a)

7485


In [37]:
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
print(x)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [38]:
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
y=random.choices(x,k=5)
print(y)

['w', 'B', 'I', 'Y', 'g']


In [39]:
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
y=random.choices(x,k=5)
s=""
for i in y:
    s=s+i
print(s)

HMpKV


In [6]:
import random
x=[]
for i in range(97,123):
    x.append(chr(i))
for i in range(65,91):
    x.append(chr(i))
for i in range(10):
    x.append(str(i))
y=random.choices(x,k=5)
s=""
for i in y:
    s=s+i
print(s)

Vj8a3


In [40]:
a=np.loadtxt("d:\load.txt")
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [41]:
a=np.loadtxt("d:\load.txt",delimiter=None)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [42]:
a=np.loadtxt("d:\load1.txt",delimiter=",")
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [43]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
a=np.full((3,4),6)
print(a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [47]:
a=np.random.randint(1,100,(3,3))
print(a)

[[53 58 27]
 [24  9 99]
 [55 75 84]]


In [48]:
a=np.random.uniform(1,100,(3,3))
print(a)

[[ 7.74013096  3.66884416 65.91187975]
 [83.30783285 93.07563707 20.872905  ]
 [89.31894754 89.9035488  75.12685343]]


In [49]:
a[2][1]

89.90354879577622

In [50]:
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
a[2][2]

1.0

In [52]:
a[2][1]=50
print(a)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. 50.  1.]]


In [55]:
print(a[1][2])
print(a[1][1])

0.0
1.0


In [56]:
a=np.random.randint(1,100,10)
print(a)

[38 29  9  3 80 33 19 10 97 22]


In [66]:
x=[1,2,3,4,5]
a=np.array([1,2,3,4,5])
print(a%2==0)
a[a%2==0]
# print(x%2==0)

[False  True False  True False]


array([2, 4])

In [65]:
x=[1,2,3,4,5]
a=np.array([1,2,3,4,5])
a[a%2==0]

array([2, 4])

In [61]:
x=[1,2,3,4,5]
y=[]
for i in x:
    if i%2==0:
        y.append(i)
print(y)

[2, 4]


In [67]:
a=np.random.randint(1,100,10)
print(a)
a[a>50]

[48 52 64 10 93  2  3 17 85 58]


array([52, 64, 93, 85, 58])

In [68]:
a=np.random.randint(1,100,10)
print(a)
a[(a>50) & (a%2==0)]

[10 96 60 80 48 31 54 12 35 19]


array([96, 60, 80, 54])

In [69]:
x=[1,2,3,4,5]
x+2

TypeError: can only concatenate list (not "int") to list

In [71]:
x=[1,2,3,4,5]
y=[]
for i in x:
    y.append(i+2)
print(y)

[3, 4, 5, 6, 7]


In [73]:
a=np.random.randint(1,100,10)
print(a)
print(a+10)

[99 96 35 39 85  2 23  7 98 84]
[109 106  45  49  95  12  33  17 108  94]


In [74]:
a=np.random.randint(1,100,10)
print(a)
a+10

[ 6  2 49 25 66 33 38 62 59 24]


array([16, 12, 59, 35, 76, 43, 48, 72, 69, 34])

In [76]:
a=np.random.randint(1,10,10)
print(a)
a*3

[2 1 1 2 7 8 8 6 3 5]


array([ 6,  3,  3,  6, 21, 24, 24, 18,  9, 15])

In [77]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)
print(a)
print(b)
a*b

[7 3 4 9 6 8 9 3 8 4]
[9 9 2 6 2 3 6 7 3 6]


array([63, 27,  8, 54, 12, 24, 54, 21, 24, 24])

In [78]:
np.square(a)

array([49,  9, 16, 81, 36, 64, 81,  9, 64, 16])

In [79]:
np.sqrt(a)

array([2.64575131, 1.73205081, 2.        , 3.        , 2.44948974,
       2.82842712, 3.        , 1.73205081, 2.82842712, 2.        ])

In [80]:
np.exp(a)

array([1096.63315843,   20.08553692,   54.59815003, 8103.08392758,
        403.42879349, 2980.95798704, 8103.08392758,   20.08553692,
       2980.95798704,   54.59815003])

In [81]:
np.log(a)

array([1.94591015, 1.09861229, 1.38629436, 2.19722458, 1.79175947,
       2.07944154, 2.19722458, 1.09861229, 2.07944154, 1.38629436])

In [82]:
np.log2(a)

array([2.80735492, 1.5849625 , 2.        , 3.169925  , 2.5849625 ,
       3.        , 3.169925  , 1.5849625 , 3.        , 2.        ])

In [83]:
np.log10(a)

array([0.84509804, 0.47712125, 0.60205999, 0.95424251, 0.77815125,
       0.90308999, 0.95424251, 0.47712125, 0.90308999, 0.60205999])

In [87]:
print(a)
print(np.mean(a))
print(np.median(a))

[7 3 4 9 6 8 9 3 8 4]
6.1
6.5


In [89]:
print(a)
print(np.min(a),np.argmin(a))
print(np.max(a),np.argmax(a))

[7 3 4 9 6 8 9 3 8 4]
3 1
9 3


In [90]:
np.bincount(a)

array([0, 0, 0, 2, 2, 0, 1, 1, 2, 2], dtype=int64)

In [91]:
a=np.array([2,3,4,2,5,2,6,2,7,2])
b=np.bincount(a)
np.argmax(b)

2

In [92]:
np.argmax(np.bincount(a))

2

In [1]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
a=np.random.randint(1,10,(3,4))
print(a)

[[7 5 8 2]
 [4 8 1 8]
 [5 8 5 5]]


In [7]:
print(a)
print(a.shape)
print(a.shape[1])
print(a.shape[0])
print(a.ndim)
print(a.dtype)
print(a.size)

[[7 5 8 2]
 [4 8 1 8]
 [5 8 5 5]]
(3, 4)
4
3
2
int32
12


In [9]:
np.reshape(a,(4,3),order='c')

array([[7, 5, 8],
       [2, 4, 8],
       [1, 8, 5],
       [8, 5, 5]])

In [10]:
np.reshape(a,(4,3),order='f')

array([[7, 8, 5],
       [4, 8, 2],
       [5, 8, 8],
       [5, 1, 5]])

In [11]:
np.reshape(a,(2,6))

array([[7, 5, 8, 2, 4, 8],
       [1, 8, 5, 8, 5, 5]])

In [12]:
np.reshape(a,(6,2))

array([[7, 5],
       [8, 2],
       [4, 8],
       [1, 8],
       [5, 8],
       [5, 5]])

In [13]:
np.reshape(a,(1,12))

array([[7, 5, 8, 2, 4, 8, 1, 8, 5, 8, 5, 5]])

In [14]:
np.reshape(a,(12,1))

array([[7],
       [5],
       [8],
       [2],
       [4],
       [8],
       [1],
       [8],
       [5],
       [8],
       [5],
       [5]])

In [16]:
np.reshape(a,(3,-1))

array([[7, 5, 8, 2],
       [4, 8, 1, 8],
       [5, 8, 5, 5]])

In [17]:
np.reshape(a,(4,-1))

array([[7, 5, 8],
       [2, 4, 8],
       [1, 8, 5],
       [8, 5, 5]])

In [18]:
np.reshape(a,(2,-1))

array([[7, 5, 8, 2, 4, 8],
       [1, 8, 5, 8, 5, 5]])

In [19]:
np.reshape(a,(-1,3))

array([[7, 5, 8],
       [2, 4, 8],
       [1, 8, 5],
       [8, 5, 5]])

In [20]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
np.append(a,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 50])

In [22]:
np.append(a,[50,60,70])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 50, 60, 70])

In [23]:
np.insert(a,1,500)

array([  0, 500,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [24]:
np.insert(a,1,[300,400,2])

array([  0, 300, 400,   2,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [25]:
np.delete(a,1)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
np.delete(a,[1,4,5,9])

array([0, 2, 3, 6, 7, 8])

In [2]:
import numpy as np
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
np.reshape(a,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.reshape(a,(4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 3D Array

In [5]:
np.reshape(a,(3,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [6]:
np.reshape(a,(2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [7]:
a=np.arange(24)

In [8]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
np.reshape(a,(3,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [10]:
np.reshape(a,(4,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [11]:
np.reshape(a,(2,3,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [12]:
np.reshape(a,(3,2,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [13]:
np.flatten()

AttributeError: module 'numpy' has no attribute 'flatten'

In [14]:
a.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
a.flatten(order='f')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
a=np.random.randint(1,10,(3,4))
print(a)

[[2 4 4 3]
 [9 6 2 7]
 [1 7 2 6]]


In [21]:
a.flatten()

array([2, 4, 4, 3, 9, 6, 2, 7, 1, 7, 2, 6])

In [22]:
a.flatten(order='f')

array([2, 9, 1, 4, 6, 7, 4, 2, 2, 3, 7, 6])

In [23]:
a=np.random.randint(1,10,5)
print(a)

[1 2 3 4 2]


In [24]:
a.max()

4

In [25]:
np.max(a)

4

In [26]:
a.min()

1

In [27]:
np.min(a)

1

In [28]:
a.flatten()

array([1, 2, 3, 4, 2])

In [29]:
np.flatten(a)

AttributeError: module 'numpy' has no attribute 'flatten'

In [30]:
np.resize(a,(3,3))

array([[1, 2, 3],
       [4, 2, 1],
       [2, 3, 4]])

In [31]:
print(a)

[1 2 3 4 2]


In [32]:
np.resize(a,(3,4))

array([[1, 2, 3, 4],
       [2, 1, 2, 3],
       [4, 2, 1, 2]])

In [33]:
a.resize((3,4))

In [34]:
a.resize((3,4),refcheck=False)
print(a)

[[1 2 3 4]
 [2 0 0 0]
 [0 0 0 0]]


In [35]:
a=np.random.randint(1,10,(3,4))
print(a)

[[2 5 9 4]
 [6 6 7 7]
 [1 2 9 4]]


In [36]:
print(np.sum(a))

62


In [37]:
print(np.sum(a,axis=1))

[20 26 16]


In [38]:
print(np.sum(a,axis=0))

[ 9 13 25 15]


In [39]:
print(np.min(a,axis=0))

[1 2 7 4]


In [40]:
print(np.max(a,axis=1))

[9 7 9]


In [41]:
print(np.max(a,axis=0))

[6 6 9 7]


In [42]:
print(np.min(a,axis=1))

[2 6 1]


In [43]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [44]:
b=np.arange(6)
print(b)

[0 1 2 3 4 5]


In [45]:
a+b

array([ 0,  2,  4,  6,  8, 10])

In [47]:
c=np.concatenate([a,b])
print(c)

[0 1 2 3 4 5 0 1 2 3 4 5]


In [49]:
a=np.random.randint(1,5,(3,4))
print(a)

[[3 2 1 1]
 [3 4 3 1]
 [2 1 4 1]]


In [50]:
b=np.random.randint(1,5,(3,4))
print(b)

[[4 1 1 4]
 [4 1 4 3]
 [3 3 2 2]]


In [51]:
c=np.concatenate([a,b],axis=None)
print(c)

[3 2 1 1 3 4 3 1 2 1 4 1 4 1 1 4 4 1 4 3 3 3 2 2]


In [53]:
c=np.concatenate([a,b])
print(c)

[[3 2 1 1]
 [3 4 3 1]
 [2 1 4 1]
 [4 1 1 4]
 [4 1 4 3]
 [3 3 2 2]]


In [54]:
c=np.concatenate([a,b])
print(c)

[[3 2 1 1]
 [3 4 3 1]
 [2 1 4 1]
 [4 1 1 4]
 [4 1 4 3]
 [3 3 2 2]]


In [56]:
c=np.concatenate([a,b],axis=1)
print(c)

[[3 2 1 1 4 1 1 4]
 [3 4 3 1 4 1 4 3]
 [2 1 4 1 3 3 2 2]]


In [57]:
a=np.random.randint(1,5,(3,4))
print(a)

[[3 1 1 2]
 [4 1 1 2]
 [1 2 3 1]]


In [59]:
b=np.random.randint(1,5,(4,3))
print(b)

[[4 3 4]
 [2 1 3]
 [4 4 4]
 [2 1 1]]


In [60]:
c=np.concatenate([a,b],axis=0)
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [61]:
c=np.concatenate([a,b],axis=1)
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [62]:
a=np.random.randint(1,5,(3,4))
print(a)

[[2 2 1 3]
 [4 2 4 1]
 [2 4 4 4]]


In [63]:
b=np.random.randint(1,5,(3,2))
print(b)

[[3 1]
 [1 2]
 [1 4]]


In [66]:
c=np.concatenate([a,b],axis=1)
print(c)

[[2 2 1 3 3 1]
 [4 2 4 1 1 2]
 [2 4 4 4 1 4]]


In [71]:
a=np.random.randint(1,5,(3,2))
print(a)

[[2 2]
 [1 2]
 [2 4]]


In [68]:
b=np.random.randint(1,5,(4,2))
print(b)

[[4 3]
 [3 4]
 [3 3]
 [2 2]]


In [72]:
c=np.concatenate([a,b],axis=0)
print(c)

[[2 2]
 [1 2]
 [2 4]
 [4 3]
 [3 4]
 [3 3]
 [2 2]]


In [73]:
a=np.random.randint(1,5,(3,4))
print(a)

[[2 1 1 1]
 [4 2 4 1]
 [1 3 4 2]]


In [74]:
b=np.random.randint(1,5,(4,3))
print(b)

[[4 3 3]
 [2 2 3]
 [1 4 3]
 [4 1 1]]


In [75]:
a=a.flatten()
print(a)

[2 1 1 1 4 2 4 1 1 3 4 2]


In [76]:
b=b.flatten()
print(b)

[4 3 3 2 2 3 1 4 3 4 1 1]


In [77]:
np.where(a==b)

(array([], dtype=int64),)

In [78]:
np.where(a>b)

(array([ 4,  6, 10, 11], dtype=int64),)

In [79]:
x=[10,5,2,5,7,5,9,5]
x.index(5)

1

In [80]:
a=np.array([10,5,2,5,7,5,9,5])
print(a)

[10  5  2  5  7  5  9  5]


In [81]:
np.where(a==5)

(array([1, 3, 5, 7], dtype=int64),)

In [82]:
a.dtype

dtype('int32')

In [83]:
a[0]=100

In [84]:
print(a)

[100   5   2   5   7   5   9   5]


In [85]:
a[0]=4.5
print(a)

[4 5 2 5 7 5 9 5]


In [86]:
a[-1]='hi'
print(a)

ValueError: invalid literal for int() with base 10: 'hi'

In [87]:
print(a)
print(a.dtype)

[4 5 2 5 7 5 9 5]
int32


In [88]:
a.astype('float')

array([4., 5., 2., 5., 7., 5., 9., 5.])

In [89]:
print(a)

[4 5 2 5 7 5 9 5]


In [90]:
a=a.astype('float')
print(a)
print(a.dtype)

[4. 5. 2. 5. 7. 5. 9. 5.]
float64


In [91]:
a[0]=4.5
print(a)

[4.5 5.  2.  5.  7.  5.  9.  5. ]


In [92]:
a=a.astype(np.float64)
a.astype('str')

array(['4.5', '5.0', '2.0', '5.0', '7.0', '5.0', '9.0', '5.0'],
      dtype='<U32')

In [93]:
a.astype('bool')

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [95]:
a=np.random.randint(1,10,5)
print(a)

[2 9 3 7 7]


In [96]:
np.delete(a,0)

array([9, 3, 7, 7])

In [101]:
a=a.astype('float')
a[0]=np.nan
print(a)

[nan  9.  3.  7.  7.]


In [102]:
a[0]=4.5
print(a)

[4.5 9.  3.  7.  7. ]


In [103]:
a=np.array([.0015,.00003456])
print(a)

[1.500e-03 3.456e-05]


In [104]:
np.set_printoptions(suppress=True)
print(a)

[0.0015     0.00003456]


In [106]:
x=list(range(5000))
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [108]:
y=np.arange(5000)
print(y)

[   0    1    2 ... 4997 4998 4999]


In [109]:
z=np.arange(999)
print(z)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [110]:
np.set_printoptions(threshold=5000)

In [111]:
print(y)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

In [112]:
a=np.array([2.5654378952873,1.4578745787327])
print(a)

[2.5654379  1.45787458]


In [113]:
np.set_printoptions(precision=12)

In [114]:
print(a)

[2.565437895287 1.457874578733]


In [115]:
np.set_printoptions(precision=25)

In [116]:
print(a)

[2.5654378952873 1.4578745787327]


In [117]:
a=np.random.randint(1,5,(3,4))
print(a)

[[1 1 2 1]
 [4 2 2 4]
 [4 3 1 3]]


In [118]:
a[:,1:3:1]

array([[1, 2],
       [2, 2],
       [3, 1]])

In [119]:
a[:,0::3]

array([[1, 1],
       [4, 4],
       [4, 3]])

In [120]:
a[1:,1:3]

array([[2, 2],
       [3, 1]])

In [121]:
a[:,2]

array([2, 2, 1])

In [122]:
a[:,2:3]

array([[2],
       [2],
       [1]])

In [123]:
a[1::1,1:3:1]

array([[2, 2],
       [3, 1]])

In [124]:
print(a)

[[1 1 2 1]
 [4 2 2 4]
 [4 3 1 3]]


In [126]:
a[1:2,0::1]

array([[4, 2, 2, 4]])

In [128]:
a[0::1,2:3:1]

array([[2],
       [2],
       [1]])

In [4]:
import numpy as np 
a=np.random.randint(1,5,(3,4))
print(a)

[[2 3 1 4]
 [4 3 3 2]
 [1 2 2 4]]


In [5]:
a[1:,2:]

array([[3, 2],
       [2, 4]])

In [6]:
a[1:,1:]

array([[3, 3, 2],
       [2, 2, 4]])

In [7]:
a[1:2,0:]

array([[4, 3, 3, 2]])

In [8]:
a[2:,0:]

array([[1, 2, 2, 4]])